version: "3.8"

services:

  depth-camera:
    # build:
    #   context: ./image
    #   dockerfile: Dockerfile
    image: wn1980/ros2-depth-camera-jazzy${TAG}
    container_name: ros2_depth_camera_jazzy
    init: true
    restart: unless-stopped
    network_mode: host
    devices:
      - "/dev:/dev"
    volumes:
      - "/dev:/dev"
    # healthcheck:
    #   test: ["CMD-SHELL", "ros2 topic list | grep /rosout"]
    #   interval: 5s
    #   timeout: 3s
    #   retries: 3
    #   start_period: 10s
    environment:
      - ROS_DOMAIN_ID=50
    # command: ["openni2_camera", "camera_with_cloud.launch.py"]
