version: "3.8"

services:

  ros2-kobuki:
    # build:
    #   context: ./image
    #   dockerfile: Dockerfile
    image: wn1980/ros2-kobuki-jazzy${TAG}
    container_name: ros2_kobuki_jazzy
    init: true
    restart: unless-stopped
    network_mode: host
    devices:
      - "/dev:/dev"
    volumes:
      - "/dev:/dev"
    healthcheck:
      test: ["CMD-SHELL", "ros2 topic list | grep /rosout"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 10s
    environment:
      - ROS_DOMAIN_ID=50
    command: ["ros2 launch /app/launch/bringup.launch.py"]

  ros2-kobuki-description:
    image: wn1980/ros2-kobuki-jazzy${TAG}
    container_name: ros2_kobuki_description_jazzy
    init: true
    restart: unless-stopped
    network_mode: host
    environment:
      - ROS_DOMAIN_ID=50
    command: ["kobuki_description", "kobuki_description.launch.py structure:=False"]
