version: "3.8"

services:
  micro-ros-agent:
    build:
      context: ./image
      dockerfile: Dockerfile
    image: wn1980/micro-ros-agent${TAG}
    container_name: ros2_micro_ros_agent_jazzy
    init: true
    restart: unless-stopped
    network_mode: host
    privileged: true
    command: udp4 --port 8888
    environment:
      - ROS_DOMAIN_ID=50
    ports:
      - "8888:8888/udp"
