version: "3.8"

services:
  micro-ros-agent:
    # build:
    #   context: ./image
    #   dockerfile: Dockerfile
    image: wn1980/micro-ros-agent${TAG}
    container_name: ros2_micro_ros_agent_jazzy
    init: true
    restart: unless-stopped
    network_mode: host
    privileged: true
    command: udp4 --port 8888
    # healthcheck:
    #   test: ["CMD-SHELL", "ros2 topic list | grep /rosout"]
    #   interval: 5s
    #   timeout: 3s
    #   retries: 3
    #   start_period: 10s
    environment:
      - ROS_DOMAIN_ID=50
    # ports:
    #   - "8888:8888/udp"
