version: "3.8"

services:
  ros2-rosbridge:
    # build:
    #   context: ./image
    #   dockerfile: Dockerfile
    image: wn1980/ros2-rosbridge-jazzy${TAG}
    container_name: ros2_rosbridge_jazzy
    init: true
    restart: unless-stopped
    network_mode: host
    healthcheck:
      test: ["CMD-SHELL", "ros2 node list | grep /rosbridge_server"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 10s
    environment:
      - ROS_DOMAIN_ID=50
    # ports:
    #   - "9090:9090"
