version: '3.8'

# create default network
#networks:
#  default:
#    external:
#      name: ros-network

volumes:
  workspace:

services:

  ros2:
    # build:
    #   context: ./image
    #   dockerfile: Dockerfile
    image: wn1980/ros2-jazzy${TAG}
    container_name: ros2_jazzy
    init: true
    restart: unless-stopped
    privileged: true
    network_mode: host
    devices:
      - "/dev:/dev"
    volumes:
      - "/dev:/dev"
      - "/run/systemd:/run/systemd"
      - "/etc/localtime:/etc/localtime:ro"
      - "workspace:/workspace"
      - "~/.gitconfig:/home/ubuntu/.gitconfig"
    healthcheck:
      test: ["CMD-SHELL", "test -e /tmp/.X11-unix/X9"]
      interval: "1m"
      retries: 20
    environment:
      - ROS_DOMAIN_ID=50
    # ports:
    #  - "8008:8008"
    #  - "6901:6901"
